# Generated by Django 3.2.20 on 2023-07-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formbuilder',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='formbuilder',
            name='html',
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='added_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
